import Head from 'next/head';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Linkedin 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <main>
        <h1 className="font-bold text-red-500">Hello</h1>
      </main>
    </div>
  );
}
